"""File size to float

Revision ID: 2d5ba759db0d
Revises: 
Create Date: 2023-08-13 23:50:30.940342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5ba759db0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20, collation='Latin1_General_CI_AS'),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20, collation='Latin1_General_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
